# Generated by Django 6.0.6 on 2026-06-27 12:24

import core.validators
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('code', models.CharField(db_index=True, help_text='ISO Country Code (e.g. IT, CA, AU)', max_length=3, unique=True)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('flag', models.ImageField(blank=True, null=True, upload_to='countries/flags/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png']), core.validators.validate_image_size])),
                ('image', models.ImageField(blank=True, help_text='Beautiful featured image of this country.', null=True, upload_to='countries/images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png']), core.validators.validate_image_size])),
                ('short_description', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Countries',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CountryFAQ',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='country.country')),
            ],
            options={
                'verbose_name': 'Country FAQ',
                'verbose_name_plural': 'Country FAQs',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CountryGallery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='countries/gallery/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png']), core.validators.validate_image_size])),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='country.country')),
            ],
            options={
                'verbose_name': 'Country Gallery',
                'verbose_name_plural': 'Country Gallery',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CountrySEO',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('keywords', models.TextField(blank=True, help_text='Separate keywords with commas.')),
                ('canonical_url', models.URLField(blank=True)),
                ('og_title', models.CharField(blank=True, max_length=255)),
                ('og_description', models.TextField(blank=True)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='countries/seo/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png']), core.validators.validate_image_size])),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seo', to='country.country')),
            ],
            options={
                'verbose_name': 'Country SEO',
                'verbose_name_plural': 'Country SEO',
            },
        ),
        migrations.CreateModel(
            name='CountryVisaRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visa_requirements', to='country.country')),
            ],
            options={
                'verbose_name': 'Country Visa Requirement',
                'verbose_name_plural': 'Country Visa Requirements',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CountryRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requirement_type', models.CharField(choices=[('VISA', 'Visa Requirement'), ('DOCUMENT', 'Document Requirement')], db_index=True, max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='country.country')),
            ],
            options={
                'verbose_name': 'Country Requirement',
                'verbose_name_plural': 'Country Requirements',
                'ordering': ['display_order', 'title'],
                'indexes': [models.Index(fields=['country', 'requirement_type'], name='country_cou_country_588abd_idx'), models.Index(fields=['country', 'is_active'], name='country_cou_country_d2e548_idx')],
                'constraints': [models.UniqueConstraint(fields=('country', 'requirement_type', 'title'), name='unique_country_requirement')],
            },
        ),
    ]
