# Generated by Django 6.0.6 on 2026-06-27 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='currency',
            field=models.CharField(default='USD', help_text='The official 3-letter currency code (e.g., USD, EUR)', max_length=3),
        ),
        migrations.DeleteModel(
            name='CountryVisaRequirement',
        ),
    ]
