# Generated by Django 6.0.6 on 2026-07-07 13:25

import cloudinary.models
import core.validators
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0002_alter_country_flag_alter_country_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='flag',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png']), core.validators.validate_image_size], verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='country',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Beautiful featured image of this country.', max_length=255, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png']), core.validators.validate_image_size], verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='countrygallery',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png']), core.validators.validate_image_size], verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='countryseo',
            name='og_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png']), core.validators.validate_image_size], verbose_name='image'),
        ),
    ]
