# Generated by Django 6.0.6 on 2026-06-27 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0002_country_currency_delete_countryvisarequirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='capital',
            field=models.CharField(blank=True, help_text='The capital city of the country (e.g., Washington D.C., Paris).', max_length=100),
        ),
        migrations.AddField(
            model_name='country',
            name='language',
            field=models.CharField(default='English', help_text='The official language of the country', max_length=50),
        ),
        migrations.AddField(
            model_name='country',
            name='processing_time',
            field=models.CharField(blank=True, help_text="Estimated processing time phrase (e.g., '3-5 business days', '2 weeks').", max_length=50),
        ),
        migrations.AddField(
            model_name='country',
            name='time_zone',
            field=models.CharField(default='UTC', help_text='The primary time zone of the country.', max_length=50),
        ),
    ]
