# Generated by Django 6.0.6 on 2026-06-27 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0003_country_capital_country_language_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='countryseo',
            old_name='keywords',
            new_name='meta_keywords',
        ),
    ]
