# Generated by Django 6.0.6 on 2026-07-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0003_alter_country_flag_alter_country_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countryrequirement',
            name='requirement_type',
            field=models.CharField(choices=[('VISA', 'Visa Requirement'), ('DOCUMENT', 'Document Requirement'), ('LANGUAGE_SKILL', 'Language Skills')], db_index=True, max_length=20),
        ),
    ]
