# Generated by Django 6.0.6 on 2026-07-05 08:44

import core.validators
import django.core.validators
import django.db.models.deletion
import staff.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agency', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=150, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Designation',
                'verbose_name_plural': 'Designations',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_id', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='staff/photo/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png']), core.validators.validate_image_size])),
                ('signature', models.ImageField(blank=True, null=True, upload_to='staff/signature/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png']), core.validators.validate_image_size])),
                ('phone', models.CharField(max_length=30)),
                ('whatsapp', models.CharField(blank=True, max_length=30)),
                ('father_name', models.CharField(max_length=200)),
                ('mother_name', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=20)),
                ('date_of_birth', models.DateField()),
                ('nationality', models.CharField(max_length=100)),
                ('nid_number', models.CharField(blank=True, max_length=50)),
                ('passport_number', models.CharField(blank=True, max_length=50)),
                ('joining_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staffs', to='staff.designation')),
                ('office', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staffs', to='agency.office')),
                ('reference_staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_staffs', to='staff.staff')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Staff',
                'verbose_name_plural': 'Staff',
                'ordering': ['employee_id'],
            },
        ),
        migrations.CreateModel(
            name='StaffDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('file', models.FileField(upload_to='staff/documents/')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='staff.staff')),
            ],
            options={
                'verbose_name': 'Staff Document',
                'verbose_name_plural': 'Staff Documents',
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='StaffEmergencyContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('relationship', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=30)),
                ('address', models.TextField(blank=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to='staff.staff')),
            ],
            options={
                'verbose_name': 'Emergency Contact',
                'verbose_name_plural': 'Emergency Contacts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StaffPublicProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('public_password_hash', models.CharField(blank=True, max_length=128)),
                ('public_fields', models.JSONField(blank=True, default=staff.models.default_public_staff_fields, help_text='List of staff profile fields that can be returned publicly.')),
                ('is_public', models.BooleanField(db_index=True, default=False)),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='public_profile', to='staff.staff')),
            ],
            options={
                'verbose_name': 'Staff Public Profile',
                'verbose_name_plural': 'Staff Public Profiles',
                'ordering': ['staff__employee_id'],
            },
        ),
        migrations.CreateModel(
            name='StaffMonthlySlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocation_month', models.DateField(help_text='Always save the first day of the month.')),
                ('total_slot', models.PositiveIntegerField()),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_slots', to='staff.staff')),
            ],
            options={
                'verbose_name': 'Staff Monthly Slot',
                'verbose_name_plural': 'Staff Monthly Slots',
                'ordering': ['-allocation_month'],
                'constraints': [models.UniqueConstraint(fields=('staff', 'allocation_month'), name='unique_staff_month_slot')],
            },
        ),
    ]
