# Generated by Django 6.0.6 on 2026-07-04 11:46

import django.db.models.deletion
import staff.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffPublicProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('public_password_hash', models.CharField(blank=True, max_length=128)),
                ('public_fields', models.JSONField(blank=True, default=staff.models.default_public_staff_fields, help_text='List of staff profile fields that can be returned publicly.')),
                ('is_public', models.BooleanField(db_index=True, default=False)),
                ('staff', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='public_profile', to='staff.staff')),
            ],
            options={
                'verbose_name': 'Staff Public Profile',
                'verbose_name_plural': 'Staff Public Profiles',
                'ordering': ['staff__employee_id'],
            },
        ),
    ]
