# Generated by Django 6.0.6 on 2026-07-05 10:03

import cloudinary.models
import core.validators
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png']), core.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='staff',
            name='signature',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png']), core.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='staffdocument',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
