# Generated by Django 6.0.6 on 2026-07-06 12:54

import cloudinary.models
import core.validators
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_alter_staff_photo_alter_staff_signature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png']), core.validators.validate_image_size], verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='signature',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png']), core.validators.validate_image_size], verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='staffdocument',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='raw'),
        ),
        migrations.CreateModel(
            name='SubStaff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('parent_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_staffs', to='staff.staff')),
            ],
            options={
                'verbose_name': 'Sub Staff',
                'verbose_name_plural': 'Sub Staff',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SubStaffMonthlySlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allocation_month', models.DateField(help_text='Always save the first day of the month.')),
                ('allocated_slot', models.PositiveIntegerField(default=0)),
                ('sub_staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monthly_slots', to='staff.substaff')),
            ],
            options={
                'verbose_name': 'Sub Staff Monthly Slot',
                'verbose_name_plural': 'Sub Staff Monthly Slots',
                'ordering': ['-allocation_month', 'sub_staff__name'],
                'constraints': [models.UniqueConstraint(fields=('sub_staff', 'allocation_month'), name='unique_sub_staff_month_slot')],
            },
        ),
    ]
