# Generated by Django 6.0.6 on 2026-07-12 21:46

import cloudinary.models
import core.validators
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_alter_staff_photo_alter_staff_signature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png']), core.validators.validate_image_size, core.validators.validate_profile_image_dimensions], verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='staff',
            name='signature',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png']), core.validators.validate_image_size, core.validators.validate_signature_dimensions], verbose_name='image'),
        ),
    ]
