# Generated by Django 6.0.6 on 2026-07-15 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0004_alter_staff_photo_alter_staff_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='smtp_email',
            field=models.EmailField(blank=True, help_text='System default SMTP email (only applies if admin).', max_length=254),
        ),
        migrations.AddField(
            model_name='staff',
            name='smtp_password',
            field=models.CharField(blank=True, help_text='System default SMTP password.', max_length=255),
        ),
    ]
