# Generated by Django 6.0.6 on 2026-07-25 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_staff_smtp_email_staff_smtp_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='fake_approved_count',
            field=models.PositiveIntegerField(default=0, help_text='Manual/fake addition to lifetime approved visa count.'),
        ),
        migrations.AddField(
            model_name='staff',
            name='fake_rejected_count',
            field=models.PositiveIntegerField(default=0, help_text='Manual/fake addition to lifetime rejected visa count.'),
        ),
    ]
