# Generated by Django 6.0.6 on 2026-07-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_staff_fake_approved_count_staff_fake_rejected_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='ranking',
            field=models.PositiveIntegerField(blank=True, help_text='Optional unique staff ranking position (e.g. 1, 2, 3).', null=True, unique=True),
        ),
    ]
