# Generated by Django 6.0.6 on 2026-07-25 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_staff_ranking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='ranking',
        ),
        migrations.AddField(
            model_name='staff',
            name='monthly_rank',
            field=models.PositiveIntegerField(blank=True, help_text='Optional staff monthly ranking position (e.g. 1, 2, 3).', null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='yearly_rank',
            field=models.PositiveIntegerField(blank=True, help_text='Optional staff yearly ranking position (e.g. 1, 2, 3).', null=True),
        ),
    ]
