# Generated by Django 6.0.6 on 2026-08-30 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_staff_fake_processing_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='employee_id',
            field=models.CharField(blank=True, db_index=True, max_length=20, unique=True),
        ),
    ]
