# Generated by Django 6.0.6 on 2026-06-28 10:26

import core.validators
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agency', '0001_initial'),
        ('country', '0004_rename_keywords_countryseo_meta_keywords'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisaCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Visa Category',
                'verbose_name_plural': 'Visa Categories',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Visa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(blank=True)),
                ('minimum_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('maximum_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('working_hours_per_week', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('overtime_available', models.BooleanField(default=False)),
                ('minimum_processing_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('maximum_processing_days', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('duration_in_months', models.PositiveSmallIntegerField(blank=True, help_text='Visa validity or contract duration in months.', null=True)),
                ('from_any_country', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visas', to='country.country')),
                ('services', models.ManyToManyField(blank=True, related_name='visas', to='agency.agencyservice')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visas', to='visa.visacategory')),
            ],
            options={
                'verbose_name': 'Visa',
                'verbose_name_plural': 'Visas',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='VisaFAQ',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.CharField(max_length=255)),
                ('answer', models.TextField()),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('visa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='visa.visa')),
            ],
            options={
                'verbose_name': 'Visa FAQ',
                'verbose_name_plural': 'Visa FAQs',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VisaRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requirement_type', models.CharField(choices=[('DOCUMENT', 'Document'), ('ELIGIBILITY', 'Eligibility'), ('BENEFIT', 'Benefit'), ('RESTRICTION', 'Restriction'), ('NOTE', 'Important Note')], db_index=True, max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_required', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('visa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='visa.visa')),
            ],
            options={
                'verbose_name': 'Visa Requirement',
                'verbose_name_plural': 'Visa Requirements',
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='VisaSEO',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(blank=True, max_length=255)),
                ('meta_description', models.TextField(blank=True)),
                ('keywords', models.TextField(blank=True, help_text='Separate keywords with commas.')),
                ('canonical_url', models.URLField(blank=True)),
                ('og_title', models.CharField(blank=True, max_length=255)),
                ('og_description', models.TextField(blank=True)),
                ('og_image', models.ImageField(blank=True, null=True, upload_to='visas/seo/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png']), core.validators.validate_image_size])),
                ('visa', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seo', to='visa.visa')),
            ],
            options={
                'verbose_name': 'Visa SEO',
                'verbose_name_plural': 'Visa SEO',
            },
        ),
        migrations.CreateModel(
            name='VisaStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('visa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='visa.visa')),
            ],
            options={
                'verbose_name': 'Visa Step',
                'verbose_name_plural': 'Visa Steps',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='visa',
            index=models.Index(fields=['country', 'category'], name='visa_visa_country_5fb711_idx'),
        ),
        migrations.AddIndex(
            model_name='visa',
            index=models.Index(fields=['country', 'is_active'], name='visa_visa_country_c95dff_idx'),
        ),
        migrations.AddIndex(
            model_name='visa',
            index=models.Index(fields=['category', 'is_active'], name='visa_visa_categor_aef156_idx'),
        ),
        migrations.AddIndex(
            model_name='visafaq',
            index=models.Index(fields=['visa', 'display_order'], name='visa_visafa_visa_id_f69210_idx'),
        ),
        migrations.AddConstraint(
            model_name='visafaq',
            constraint=models.UniqueConstraint(fields=('visa', 'question'), name='unique_visa_question'),
        ),
        migrations.AddIndex(
            model_name='visarequirement',
            index=models.Index(fields=['visa', 'requirement_type'], name='visa_visare_visa_id_50cd4d_idx'),
        ),
        migrations.AddIndex(
            model_name='visarequirement',
            index=models.Index(fields=['visa', 'is_active'], name='visa_visare_visa_id_c2978e_idx'),
        ),
        migrations.AddConstraint(
            model_name='visarequirement',
            constraint=models.UniqueConstraint(fields=('visa', 'requirement_type', 'title'), name='unique_visa_requirement'),
        ),
        migrations.AddIndex(
            model_name='visastep',
            index=models.Index(fields=['visa', 'display_order'], name='visa_visast_visa_id_506961_idx'),
        ),
        migrations.AddConstraint(
            model_name='visastep',
            constraint=models.UniqueConstraint(fields=('visa', 'title'), name='unique_visa_step'),
        ),
    ]
