# Generated by Django 6.0.6 on 2026-06-29 08:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisaJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('minimum_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('maximum_salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(default='EUR', max_length=10)),
                ('vacancies', models.PositiveIntegerField(blank=True, null=True)),
                ('experience_required', models.CharField(blank=True, help_text='Example: Fresher, 1 Year, 2 Years', max_length=100)),
                ('duty_days_per_week', models.PositiveSmallIntegerField(blank=True, help_text='Example: 6', null=True)),
                ('duty_hours_per_day', models.DecimalField(blank=True, decimal_places=1, help_text='Example: 8.0', max_digits=4, null=True)),
                ('overtime_available', models.BooleanField(default=False)),
                ('overtime_rate', models.CharField(blank=True, help_text='Example: €8/hour', max_length=100)),
                ('accommodation', models.BooleanField(default=False)),
                ('food', models.BooleanField(default=False)),
                ('medical', models.BooleanField(default=False)),
                ('transportation', models.BooleanField(default=False)),
                ('insurance', models.BooleanField(default=False)),
                ('air_ticket', models.BooleanField(default=False, help_text='Provided by employer.')),
                ('contract_duration_months', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('probation_period_months', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('location', models.CharField(blank=True, help_text='Example: Milan, Rome', max_length=150)),
                ('language_requirement', models.CharField(blank=True, max_length=150)),
                ('education_requirement', models.CharField(blank=True, max_length=150)),
                ('gender_preference', models.CharField(blank=True, help_text='Optional', max_length=50)),
                ('age_requirement', models.CharField(blank=True, help_text='Example: 21-35 Years', max_length=100)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('visa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='visa.visa')),
            ],
            options={
                'verbose_name': 'Visa Job',
                'verbose_name_plural': 'Visa Jobs',
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='JobFacility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facilities', to='visa.visajob')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='visajob',
            index=models.Index(fields=['visa', 'is_active'], name='visa_visajo_visa_id_6bc535_idx'),
        ),
        migrations.AddConstraint(
            model_name='visajob',
            constraint=models.UniqueConstraint(fields=('visa', 'title'), name='unique_visa_job'),
        ),
    ]
