# Generated by Django 6.0.6 on 2026-07-07 13:25

import cloudinary.models
import core.validators
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0002_alter_visaseo_og_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visaseo',
            name='og_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png']), core.validators.validate_image_size], verbose_name='image'),
        ),
    ]
