# Generated by Django 6.0.6 on 2026-07-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visa', '0003_alter_visaseo_og_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visarequirement',
            name='requirement_type',
            field=models.CharField(choices=[('DOCUMENT', 'Document'), ('ELIGIBILITY', 'Eligibility'), ('BENEFIT', 'Benefit'), ('RESTRICTION', 'Restriction'), ('NOTE', 'Important Note'), ('LANGUAGE_SKILL', 'Language Skills')], db_index=True, max_length=20),
        ),
    ]
