"""
Django settings for Visa_Web_Service project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from decouple import config
from pathlib import Path
import cloudinary

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY', default='django-insecure-k#r_t)39iz#oh9io@^9w_!d7cw^3cxtz+0!pc%j!nw=3oc3#-v')

#curencyFreaks API Key
CURRENCY_FREAKS_API_KEY = '9dd60838f25843248421b75e23067a9f'

# Currency cache configuration
CURRENCY_RATE_TARGET_CURRENCY = "EUR"
CURRENCY_RATE_MAX_AGE_HOURS = 24

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', default=False, cast=bool)

ALLOWED_HOSTS = config(
    'ALLOWED_HOSTS',
    default='localhost,127.0.0.1,0.0.0.0',
    cast=lambda value: [item.strip() for item in value.split(',') if item.strip()],
)

CSRF_TRUSTED_ORIGINS = config(
    'CSRF_TRUSTED_ORIGINS',
    default='http://localhost:8000,http://127.0.0.1:8000',
    cast=lambda value: [item.strip() for item in value.split(',') if item.strip()],
)

CORS_ALLOW_ALL_ORIGINS = config('CORS_ALLOW_ALL_ORIGINS', default=True, cast=bool)

# Application definition

INSTALLED_APPS = [
    'corsheaders',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    "whitenoise.runserver_nostatic",
    'django.contrib.staticfiles',
    'cloudinary_storage',
    "debug_toolbar",
    "rest_framework",
    "drf_spectacular",
    'django_filters',
    "core",
    "country",
    "visa",
    "applicant",
    "cms",
    "communication",
    "staff",
    "api",
    "agency",
]

MIDDLEWARE = [
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Visa_Web_Service.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

INTERNAL_IPS = [
    # ...
    "127.0.0.1",
    # ...
]

WSGI_APPLICATION = 'Visa_Web_Service.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': config('DB_NAME'),
        'USER': config('DB_USER'),
        'PASSWORD': config('DB_PASSWORD'),
        'HOST': config('DB_HOST'),
        'PORT': config('DB_PORT', default='5432'),
        'OPTIONS': {
            'sslmode': config('DB_SSLMODE', default='require'),
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

CLOUDINARY_CLOUD_NAME = config('CLOUDINARY_CLOUD_NAME', default=config('cloud_name', default=''))
CLOUDINARY_API_KEY = config('CLOUDINARY_API_KEY', default=config('cloudinary_api_key', default=''))
CLOUDINARY_API_SECRET = config('CLOUDINARY_API_SECRET', default=config('api_secret', default=''))

cloudinary.config(
    cloud_name=CLOUDINARY_CLOUD_NAME,
    api_key=CLOUDINARY_API_KEY,
    api_secret=CLOUDINARY_API_SECRET,
)

DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"
STATICFILES_STORAGE = "whitenoise.storage.CompressedStaticFilesStorage"

MEDIA_URL = '/media/'

MEDIA_ROOT = BASE_DIR / 'media'


REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "rest_framework.authentication.SessionAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": (
        "rest_framework.permissions.IsAuthenticatedOrReadOnly",
    ),
}

from datetime import timedelta
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=8),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": False,
    "AUTH_HEADER_TYPES": ("Bearer",),
}


SPECTACULAR_SETTINGS = {
    "TITLE": "Visa Agency Platform API",
    "DESCRIPTION": """
REST API documentation for the Visa Agency Platform.

Public frontend features include country and visa directories, public notices,
applicant status tracking, current-month staff slots, protected staff profiles,
and public approved/rejected applicant results.

Authenticated admin/staff features include applicant management, status updates,
email dispatch through assigned lawyers, payments, refunds, agreements, staff
management, CMS content, country and visa management, and agency operations.
""",
    "VERSION": "1.0.0",
    "TERMS_OF_SERVICE": "https://www.google.com/policies/terms/",
    "CONTACT": {
        "name": "Visa Agency Platform API Support",
        "email": "contact@visaagency.com",
    },
    "LICENSE": {
        "name": "BSD License",
    },    "SERVE_INCLUDE_SCHEMA": False,
    "COMPONENT_SPLIT_REQUEST": True,
    "TAGS": [
        {
            "name": "Public",
            "description": "Unauthenticated endpoints used by the public React frontend.",
        },
        {
            "name": "Countries",
            "description": "Public country directory and admin country CMS resources.",
        },
        {
            "name": "Visas",
            "description": "Visa categories, standard visas, job visas, requirements, steps, FAQs, SEO, and facilities.",
        },
        {
            "name": "Applicants",
            "description": "Authenticated applicant pipeline, payments, refunds, documents, notes, and status history.",
        },
        {
            "name": "Staff",
            "description": "Authenticated staff profiles, monthly slots, documents, emergency contacts, and public profile settings.",
        },
        {
            "name": "Agency",
            "description": "Company information, branches, notices, reviews, services, social links, lawyers, email templates, and contact submissions.",
        },
        {
            "name": "Agreements",
            "description": "Dynamic legal agreement templates and clauses used for applicant agreement generation.",
        },
        {
            "name": "Finance",
            "description": "Currency rates, applicant payments, money receipts, refunds, and refund receipts.",
        },
    ],
}

# CORS Configuration
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]
