# Generated by Django 6.0.6 on 2026-07-05 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agency', '0001_initial'),
        ('applicant', '0001_initial'),
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='status',
            field=models.OneToOneField(blank=True, help_text='Used for automatic applicant status emails.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_template', to='applicant.applicationstatus'),
        ),
        migrations.AddField(
            model_name='lawyer',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lawyers', to='country.country'),
        ),
        migrations.AddField(
            model_name='office',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='agency.companyinformation'),
        ),
        migrations.AddField(
            model_name='sociallink',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='agency.companyinformation'),
        ),
        migrations.AddConstraint(
            model_name='lawyer',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='unique_default_lawyer'),
        ),
    ]
