# Generated by Django 6.0.6 on 2026-06-28 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyinformation',
            name='email',
        ),
        migrations.RemoveField(
            model_name='companyinformation',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='companyinformation',
            name='google_map',
        ),
        migrations.RemoveField(
            model_name='companyinformation',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='companyinformation',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='companyinformation',
            name='website',
        ),
        migrations.RemoveField(
            model_name='companyinformation',
            name='whatsapp',
        ),
        migrations.RemoveField(
            model_name='companyinformation',
            name='youtube',
        ),
        migrations.RemoveField(
            model_name='office',
            name='google_map',
        ),
        migrations.RemoveField(
            model_name='office',
            name='whatsapp',
        ),
        migrations.AddField(
            model_name='office',
            name='company',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='offices', to='agency.companyinformation'),
            preserve_default=False,
        ),
    ]
