# Generated by Django 6.0.6 on 2026-06-30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_remove_companyinformation_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='office',
            old_name='office_name',
            new_name='branch_name',
        ),
    ]
