# Generated by Django 6.0.6 on 2026-07-07 13:25

import cloudinary.models
import core.validators
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0003_alter_companyinformation_company_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinformation',
            name='company_logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png']), core.validators.validate_image_size], verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='favicon',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png']), core.validators.validate_image_size], verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='attachment',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Optional notice attachment. Allowed: PDF, JPG, JPEG, PNG. Max size: 10 MB.', max_length=255, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), core.validators.validate_document_size], verbose_name='raw'),
        ),
    ]
