# Generated by Django 6.0.6 on 2026-07-01 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0003_rename_office_name_to_branch_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='office',
            options={'ordering': ['display_order', 'branch_name'], 'verbose_name': 'Branch', 'verbose_name_plural': 'Branches'},
        ),
        migrations.AlterField(
            model_name='office',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='agency.companyinformation'),
        ),
    ]
