# Generated by Django 6.0.6 on 2026-07-03 16:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0004_alter_office_options_alter_office_company'),
        ('applicant', '0003_currencyrate_applicantpayment_currency_rate'),
        ('country', '0004_rename_keywords_countryseo_meta_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailtemplate',
            name='status',
            field=models.OneToOneField(blank=True, help_text='Used for automatic applicant status emails.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_template', to='applicant.applicationstatus'),
        ),
        migrations.CreateModel(
            name='EmailSender',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('env_key', models.CharField(help_text='Reads credentials from <ENV_KEY>_EMAIL and <ENV_KEY>_PASSWORD.', max_length=100, unique=True)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_senders', to='country.country')),
            ],
            options={
                'verbose_name': 'Email Sender',
                'verbose_name_plural': 'Email Senders',
                'ordering': ['-is_default', 'name'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('is_default',), name='unique_default_email_sender')],
            },
        ),
    ]
