# Generated by Django 6.0.6 on 2026-07-10 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0004_alter_companyinformation_company_logo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinformation',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='companyinformation',
            name='website',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
