# Generated by Django 6.0.6 on 2026-07-03 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0006_lawyer'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='emailsender',
            name='unique_default_email_sender',
        ),
        migrations.DeleteModel(
            name='EmailSender',
        ),
    ]
