# Generated by Django 6.0.6 on 2026-07-14 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0006_applicationrequest'),
        ('visa', '0003_alter_visaseo_og_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationrequest',
            name='target_visa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application_requests', to='visa.visa'),
        ),
    ]
