# Generated by Django 6.0.6 on 2026-07-18 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0007_applicationrequest_target_visa'),
    ]

    operations = [
        migrations.AddField(
            model_name='lawyer',
            name='smtp_password',
            field=models.CharField(blank=True, help_text='Gmail SMTP App Password for sending emails.', max_length=255),
        ),
        migrations.AlterField(
            model_name='lawyer',
            name='env_key',
            field=models.CharField(blank=True, help_text='Reads credentials from <ENV_KEY>_EMAIL and <ENV_KEY>_PASSWORD.', max_length=100, null=True, unique=True),
        ),
    ]
