# Generated by Django 6.0.6 on 2026-07-18 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0008_lawyer_smtp_password_alter_lawyer_env_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinformation',
            name='tagline',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
