# Generated by Django 6.0.6 on 2026-07-21 04:59

import cloudinary.models
import core.validators
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0009_companyinformation_tagline'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png']), core.validators.validate_image_size], verbose_name='image')),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='agency.companyinformation')),
            ],
            options={
                'verbose_name': 'Agency Image',
                'verbose_name_plural': 'Agency Images',
                'ordering': ['display_order', '-created_at'],
            },
        ),
    ]
