# Generated by Django 6.0.6 on 2026-07-23 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0010_agencyimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sociallink',
            options={'ordering': ['display_order', 'id']},
        ),
        migrations.AddField(
            model_name='lawyer',
            name='address',
            field=models.TextField(blank=True, default='', help_text="Lawyer's office address."),
        ),
    ]
