# Generated by Django 6.0.6 on 2026-07-23 16:15

import cloudinary.models
import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0011_alter_sociallink_options_lawyer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinformation',
            name='company_signature',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png']), core.validators.validate_image_size], verbose_name='image'),
        ),
        migrations.AddField(
            model_name='companyinformation',
            name='whatsapp',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='body',
            field=models.TextField(help_text='\nAvailable Variables:\n\n{{ applicant_name }}\n\n{{ applicant_id }}\n\n{{ father_name }}\n\n{{ nid }}\n\n{{ passport_number }}\n\n{{ job }}\n\n{{ visa }}\n\n{{ country }}\n\n{{ lawyer_name }}\n\n{{ lawyer_address }}\n\n{{ staff }}\n\n{{ current_status }}\n'),
        ),
    ]
