# Generated by Django 6.0.6 on 2026-07-24 20:06

import cloudinary.models
import core.validators
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0012_companyinformation_company_signature_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyLogo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Title or variation name of the logo (e.g. Primary Header Logo, Reverse Dark Logo, Monochrome Logo)', max_length=200)),
                ('serial_number', models.PositiveIntegerField(default=1, help_text='Serial number / order for display sorting')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png']), core.validators.validate_image_size], verbose_name='image')),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logos', to='agency.companyinformation')),
            ],
            options={
                'verbose_name': 'Company Logo',
                'verbose_name_plural': 'Company Logos',
                'ordering': ['serial_number', '-created_at'],
            },
        ),
    ]
