# Generated by Django 6.0.6 on 2026-07-24 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0013_companylogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinformation',
            name='money_receipt_important_note',
            field=models.TextField(blank=True, default="If the Visa Application has been officially submitted but the visa is not approved, and the candidate's overseas assignment is not completed within timeframe, refund shall be processed as per signed agreement clauses upon written request.", help_text='Default important note printed on money receipts.'),
        ),
    ]
