# Generated by Django 6.0.6 on 2026-07-24 20:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0014_companyinformation_money_receipt_important_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportantNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Title / preset name for the note (e.g. Standard Refund Policy, Tourist Visa Terms)', max_length=255)),
                ('content', models.TextField(help_text='Full text of the important note.')),
                ('is_default', models.BooleanField(default=False, help_text='Set as default important note for new payments')),
                ('is_active', models.BooleanField(default=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='important_notes', to='agency.companyinformation')),
            ],
            options={
                'verbose_name': 'Important Note',
                'verbose_name_plural': 'Important Notes',
                'ordering': ['-is_default', 'title'],
            },
        ),
    ]
