# Generated by Django 6.0.6 on 2026-07-27 05:30

import cloudinary.models
import core.validators
import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0015_importantnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinformation',
            name='manual_approved_count',
            field=models.PositiveIntegerField(default=0, help_text='Manually inflated approved count for dashboard stats.'),
        ),
        migrations.AddField(
            model_name='companyinformation',
            name='manual_exchange_rate',
            field=models.DecimalField(decimal_places=4, default=Decimal('140.6900'), help_text='Manual exchange rate for 1 EUR to BDT.', max_digits=10),
        ),
        migrations.AddField(
            model_name='companyinformation',
            name='manual_processing_count',
            field=models.PositiveIntegerField(default=0, help_text='Manually inflated processing count for dashboard stats.'),
        ),
        migrations.AddField(
            model_name='companyinformation',
            name='manual_rejected_count',
            field=models.PositiveIntegerField(default=0, help_text='Manually inflated rejected count for dashboard stats.'),
        ),
        migrations.AddField(
            model_name='companyinformation',
            name='use_manual_exchange_rate',
            field=models.BooleanField(default=False, help_text='If enabled, bypass API and use the manual exchange rate for EUR to BDT.'),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='company_signature',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png']), core.validators.validate_image_size, core.validators.validate_signature_dimensions], verbose_name='image'),
        ),
    ]
