# Generated by Django 6.0.6 on 2026-08-30 11:04

import cloudinary.models
import core.validators
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0017_emailtemplate_generous_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agencyimage',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), core.validators.validate_image_size], verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='company_logo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), core.validators.validate_image_size], verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='company_signature',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), core.validators.validate_image_size, core.validators.validate_signature_dimensions], verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='companyinformation',
            name='favicon',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), core.validators.validate_image_size], verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='companylogo',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), core.validators.validate_image_size], verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='attachment',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='Optional notice attachment. Allowed: PDF, JPG, JPEG, PNG. Max size: 10 MB.', max_length=255, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp']), core.validators.validate_document_size], verbose_name='raw'),
        ),
    ]
