# Generated by Django 6.0.6 on 2026-07-01 07:33

import applicant.utils
import core.validators
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('country', '0004_rename_keywords_countryseo_meta_keywords'),
        ('staff', '0001_initial'),
        ('visa', '0002_visajob_jobfacility_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=60, unique=True)),
                ('color', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Applicant Tag',
                'verbose_name_plural': 'Applicant Tags',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ApplicationStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(blank=True, help_text='Badge color used in dashboard.', max_length=20)),
                ('is_default', models.BooleanField(default=False, help_text='Automatically assigned to new applicants.')),
                ('is_final', models.BooleanField(default=False, help_text='Approved / Rejected / Delivered etc.')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Application Status',
                'verbose_name_plural': 'Application Statuses',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AgreementTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(help_text='Supports placeholders like {full_name}, {passport_number}, {visa}, {job}, {country}.')),
                ('version', models.PositiveIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('visa', models.ForeignKey(blank=True, help_text='Leave blank for a generic agreement.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agreement_templates', to='visa.visa')),
            ],
            options={
                'verbose_name': 'Agreement Template',
                'verbose_name_plural': 'Agreement Templates',
                'ordering': ['-version', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('application_id', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('full_name', models.CharField(db_index=True, max_length=200)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=applicant.utils.applicant_photo_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png']), core.validators.validate_image_size])),
                ('passport_number', models.CharField(db_index=True, max_length=20, validators=[core.validators.validate_passport_number])),
                ('passport_issue_date', models.DateField(blank=True, null=True)),
                ('passport_expiry_date', models.DateField(blank=True, null=True)),
                ('nid_number', models.CharField(blank=True, max_length=20, validators=[core.validators.validate_nid_number])),
                ('date_of_birth', models.DateField()),
                ('place_of_birth', models.CharField(blank=True, max_length=150)),
                ('current_country', models.CharField(blank=True, help_text='Current country of residence.', max_length=100)),
                ('remarks', models.TextField(blank=True, help_text='Internal permanent remarks.')),
                ('agreement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='applicants', to='applicant.agreementtemplate')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_applicants', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applicants', to='visa.visajob')),
                ('slot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicants', to='staff.staffmonthlyslot')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_applicants', to=settings.AUTH_USER_MODEL)),
                ('visa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applicants', to='visa.visa')),
                ('tags', models.ManyToManyField(blank=True, related_name='applicants', to='applicant.applicanttag')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applicants', to='applicant.applicationstatus')),
            ],
            options={
                'verbose_name': 'Applicant',
                'verbose_name_plural': 'Applicants',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicantDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(choices=[('PASSPORT', 'Passport'), ('BIRTH_CERTIFICATE', 'Birth Certificate'), ('NID', 'National ID'), ('PHOTO', 'Photograph'), ('IELTS', 'IELTS Certificate'), ('BANK_STATEMENT', 'Bank Statement'), ('MEDICAL', 'Medical Report'), ('POLICE_CLEARANCE', 'Police Clearance'), ('EDUCATIONAL', 'Educational Certificate'), ('OTHER', 'Other')], max_length=30)),
                ('title', models.CharField(blank=True, help_text="Required when document type is 'Other'.", max_length=150)),
                ('file', models.FileField(upload_to='applicants/documents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), core.validators.validate_document_size])),
                ('remarks', models.TextField(blank=True, help_text='Admin remarks regarding this document.')),
                ('verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='applicant.applicant')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to='staff.staff')),
            ],
            options={
                'verbose_name': 'Applicant Document',
                'verbose_name_plural': 'Applicant Documents',
                'ordering': ['document_type', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicantNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.TextField()),
                ('is_private', models.BooleanField(default=True, help_text='Private notes are visible only to internal staff.')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='applicant.applicant')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applicant_notes', to='staff.staff')),
            ],
            options={
                'verbose_name': 'Applicant Note',
                'verbose_name_plural': 'Applicant Notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicantProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('father_name', models.CharField(blank=True, max_length=150)),
                ('mother_name', models.CharField(blank=True, max_length=150)),
                ('phone', models.CharField(blank=True, max_length=20, validators=[core.validators.validate_phone_number])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('occupation', models.CharField(blank=True, max_length=150)),
                ('highest_education', models.CharField(blank=True, max_length=150)),
                ('religion', models.CharField(blank=True, max_length=100)),
                ('marital_status', models.CharField(blank=True, choices=[('SINGLE', 'Single'), ('MARRIED', 'Married'), ('DIVORCED', 'Divorced'), ('WIDOWED', 'Widowed')], max_length=20)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10)),
                ('nationality', models.CharField(blank=True, max_length=100)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=150)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=20, validators=[core.validators.validate_phone_number])),
                ('emergency_contact_relation', models.CharField(blank=True, max_length=100)),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='applicant.applicant')),
            ],
            options={
                'verbose_name': 'Applicant Profile',
                'verbose_name_plural': 'Applicant Profiles',
            },
        ),
        migrations.CreateModel(
            name='ApplicantStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('remarks', models.TextField(blank=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='applicant.applicant')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_changes', to='staff.staff')),
                ('new_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='applicant.applicationstatus')),
                ('old_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='applicant.applicationstatus')),
            ],
            options={
                'verbose_name': 'Applicant Status History',
                'verbose_name_plural': 'Applicant Status Histories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicantAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('address_type', models.CharField(choices=[('PRESENT', 'Present'), ('PERMANENT', 'Permanent')], max_length=20)),
                ('village', models.CharField(blank=True, max_length=150)),
                ('post_office', models.CharField(blank=True, max_length=150)),
                ('police_station', models.CharField(blank=True, max_length=150)),
                ('district', models.CharField(blank=True, max_length=150)),
                ('extra_fields', models.JSONField(blank=True, default=dict, help_text='Flexible address data for non-Bangladesh addresses (state, province, zip code, etc.).')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='applicant.applicant')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applicant_addresses', to='country.country')),
            ],
            options={
                'verbose_name': 'Applicant Address',
                'verbose_name_plural': 'Applicant Addresses',
                'ordering': ['address_type'],
                'constraints': [models.UniqueConstraint(fields=('applicant', 'address_type'), name='unique_applicant_address_type')],
            },
        ),
        migrations.CreateModel(
            name='ApplicantPayment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('payment_number', models.PositiveIntegerField(editable=False, help_text='Auto-generated payment sequence per applicant.')),
                ('receipt_number', models.CharField(blank=True, max_length=50)),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('CASH', 'Hand Cash'), ('BANK', 'Bank Transfer'), ('MOBILE_BANKING', 'Mobile Banking'), ('CHEQUE', 'Cheque'), ('ONLINE', 'Online Payment')], max_length=20)),
                ('currency', models.CharField(help_text='ISO Currency Code (USD, EUR, BDT, etc.).', max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('exchange_rate', models.DecimalField(decimal_places=4, help_text='Exchange rate used during payment.', max_digits=12)),
                ('euro_amount', models.DecimalField(decimal_places=2, editable=False, help_text='Calculated automatically.', max_digits=12)),
                ('reference', models.CharField(blank=True, help_text='Bank transaction / Bkash / Nagad reference.', max_length=100)),
                ('note', models.TextField(blank=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='applicant.applicant')),
                ('received_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_payments', to='staff.staff')),
            ],
            options={
                'verbose_name': 'Applicant Payment',
                'verbose_name_plural': 'Applicant Payments',
                'ordering': ['payment_number'],
                'constraints': [models.UniqueConstraint(fields=('applicant', 'payment_number'), name='unique_payment_number_per_applicant')],
            },
        ),
        migrations.AddIndex(
            model_name='applicant',
            index=models.Index(fields=['application_id'], name='applicant_a_applica_ba2dc2_idx'),
        ),
        migrations.AddIndex(
            model_name='applicant',
            index=models.Index(fields=['passport_number'], name='applicant_a_passpor_cd5828_idx'),
        ),
        migrations.AddIndex(
            model_name='applicant',
            index=models.Index(fields=['status'], name='applicant_a_status__001f7e_idx'),
        ),
        migrations.AddIndex(
            model_name='applicant',
            index=models.Index(fields=['visa'], name='applicant_a_visa_id_28dfff_idx'),
        ),
        migrations.AddIndex(
            model_name='applicant',
            index=models.Index(fields=['job'], name='applicant_a_job_id_809176_idx'),
        ),
        migrations.AddIndex(
            model_name='applicant',
            index=models.Index(fields=['slot'], name='applicant_a_slot_id_70e319_idx'),
        ),
        migrations.AddConstraint(
            model_name='applicant',
            constraint=models.UniqueConstraint(fields=('passport_number', 'visa', 'job'), name='unique_passport_visa_job'),
        ),
    ]
