# Generated by Django 6.0.6 on 2026-07-01 07:41

import applicant.utils
import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantdocument',
            name='file',
            field=models.FileField(upload_to=applicant.utils.applicant_document_upload_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), core.validators.validate_document_size]),
        ),
    ]
