# Generated by Django 6.0.6 on 2026-07-03 12:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0002_alter_applicantdocument_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyRate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('base_currency', models.CharField(db_index=True, help_text='Source ISO currency code.', max_length=3)),
                ('target_currency', models.CharField(db_index=True, default='EUR', help_text='Target ISO currency code.', max_length=3)),
                ('rate', models.DecimalField(decimal_places=6, help_text='Exchange rate from base to target currency.', max_digits=18)),
                ('source', models.CharField(default='CurrencyFreaks', max_length=100)),
                ('fetched_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('raw_response', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Currency Rate',
                'verbose_name_plural': 'Currency Rates',
                'ordering': ['-fetched_at', 'base_currency', 'target_currency'],
                'constraints': [models.UniqueConstraint(fields=('base_currency', 'target_currency'), name='unique_currency_rate_pair')],
            },
        ),
        migrations.AddField(
            model_name='applicantpayment',
            name='currency_rate',
            field=models.ForeignKey(blank=True, help_text='Stored exchange rate snapshot used for this payment.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='applicant.currencyrate'),
        ),
    ]
