# Generated by Django 6.0.6 on 2026-07-06 19:52

import cloudinary.models
import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0003_seed_new_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantrefund',
            name='cheque_bank_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='applicantrefund',
            name='cheque_branch_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='applicantrefund',
            name='cheque_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicantrefund',
            name='cheque_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='applicantrefund',
            name='received_by_name',
            field=models.CharField(blank=True, help_text='Name of the person who collected the cash/cheque.', max_length=200),
        ),
        migrations.AddField(
            model_name='applicantrefund',
            name='refund_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Hand Cash'), ('BANK', 'Bank Transfer'), ('MOBILE_BANKING', 'Mobile Banking'), ('CHEQUE', 'Cheque'), ('ONLINE', 'Online Payment')], max_length=20),
        ),
        migrations.AddField(
            model_name='applicantrefundreceipt',
            name='cheque_bank_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='applicantrefundreceipt',
            name='cheque_branch_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='applicantrefundreceipt',
            name='cheque_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicantrefundreceipt',
            name='cheque_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='applicantrefundreceipt',
            name='received_by_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='applicantrefundreceipt',
            name='refund_method',
            field=models.CharField(blank=True, choices=[('CASH', 'Hand Cash'), ('BANK', 'Bank Transfer'), ('MOBILE_BANKING', 'Mobile Banking'), ('CHEQUE', 'Cheque'), ('ONLINE', 'Online Payment')], max_length=20),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png']), core.validators.validate_image_size], verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='applicantdocument',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png']), core.validators.validate_document_size], verbose_name='raw'),
        ),
    ]
