# Generated by Django 6.0.6 on 2026-07-03 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0007_remove_emailsender_unique_default_email_sender_and_more'),
        ('applicant', '0003_currencyrate_applicantpayment_currency_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='lawyer',
            field=models.ForeignKey(blank=True, help_text="Dedicated lawyer for this applicant's email communication.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicants', to='agency.lawyer'),
        ),
    ]
