# Generated by Django 6.0.6 on 2026-07-07 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0004_applicantrefund_cheque_bank_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantprofile',
            name='preferred_refund_method',
            field=models.CharField(blank=True, choices=[('bank', 'Bank Transfer'), ('cheque', 'Cheque'), ('cash', 'Cash')], default='bank', max_length=20),
        ),
    ]
