# Generated by Django 6.0.6 on 2026-07-03 20:39

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0004_applicant_lawyer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='payment_plan_installments',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Two Installments'), (3, 'Three Installments')], default=2, help_text='Total expected payment installments for this applicant.'),
        ),
        migrations.AddField(
            model_name='applicantpayment',
            name='installment_type',
            field=models.CharField(choices=[('INITIAL', 'Initial Payment'), ('SECOND', 'Second Installment'), ('THIRD', 'Third Installment')], db_index=True, default='INITIAL', help_text='Identifies refund bucket and payment progress.', max_length=20),
        ),
        migrations.CreateModel(
            name='ApplicantRefund',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('refund_status', models.CharField(choices=[('bank_info_missing', 'Bank Info Missing'), ('pending', 'Pending'), ('approved', 'Approved'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=30)),
                ('refund_type', models.CharField(choices=[('partial', 'Partial Refund'), ('full', 'Full Refund')], default='partial', max_length=20)),
                ('refund_basis', models.CharField(choices=[('payment', 'Payment Based'), ('agreement', 'Agreement Based'), ('other', 'Other')], default='payment', max_length=20)),
                ('refund_percentage', models.DecimalField(decimal_places=2, default=Decimal('80.00'), max_digits=5)),
                ('refundable_payment_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('non_refundable_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('refund_reason', models.TextField(blank=True)),
                ('refund_date', models.DateField(default=django.utils.timezone.localdate)),
                ('generated_from_rejection', models.BooleanField(db_index=True, default=False)),
                ('bank_detail_snapshot', models.JSONField(blank=True, default=dict)),
                ('payment_summary_snapshot', models.JSONField(blank=True, default=dict)),
                ('applicant_snapshot', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refunds', to='applicant.applicant')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_applicant_refunds', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_applicant_refunds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Applicant Refund',
                'verbose_name_plural': 'Applicant Refunds',
                'ordering': ['-refund_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicantRefundBankDetail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account_holder_name', models.CharField(blank=True, max_length=200)),
                ('bank_name', models.CharField(blank=True, max_length=200)),
                ('branch_name', models.CharField(blank=True, max_length=200)),
                ('district_name', models.CharField(blank=True, max_length=150)),
                ('account_number_or_iban', models.CharField(blank=True, max_length=100)),
                ('routing_number', models.CharField(blank=True, max_length=100)),
                ('mobile_number', models.CharField(blank=True, max_length=30)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='refund_bank_detail', to='applicant.applicant')),
            ],
            options={
                'verbose_name': 'Applicant Refund Bank Detail',
                'verbose_name_plural': 'Applicant Refund Bank Details',
            },
        ),
        migrations.CreateModel(
            name='ApplicantRefundReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receipt_number', models.CharField(db_index=True, max_length=60, unique=True)),
                ('receipt_type', models.CharField(choices=[('MONEY_RECEIPT', 'Money Receipt'), ('REFUND_RECEIPT', 'Refund Receipt')], default='REFUND_RECEIPT', max_length=30)),
                ('refund_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('refundable_payment_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('non_refundable_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('refund_reason', models.TextField(blank=True)),
                ('refund_bank_snapshot', models.JSONField(blank=True, default=dict)),
                ('applicant_snapshot', models.JSONField(blank=True, default=dict)),
                ('payment_summary_snapshot', models.JSONField(blank=True, default=dict)),
                ('summary_text', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_void', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_receipts', to='applicant.applicant')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_refund_receipts', to=settings.AUTH_USER_MODEL)),
                ('refund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='applicant.applicantrefund')),
            ],
            options={
                'verbose_name': 'Applicant Refund Receipt',
                'verbose_name_plural': 'Applicant Refund Receipts',
                'ordering': ['-generated_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicantMoneyReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('receipt_number', models.CharField(db_index=True, max_length=60, unique=True)),
                ('receipt_type', models.CharField(choices=[('MONEY_RECEIPT', 'Money Receipt'), ('REFUND_RECEIPT', 'Refund Receipt')], default='MONEY_RECEIPT', max_length=30)),
                ('payment_reference', models.CharField(blank=True, max_length=100)),
                ('installment_type', models.CharField(choices=[('INITIAL', 'Initial Payment'), ('SECOND', 'Second Installment'), ('THIRD', 'Third Installment')], max_length=20)),
                ('installment_label', models.CharField(blank=True, max_length=100)),
                ('payment_number', models.PositiveIntegerField()),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(choices=[('CASH', 'Hand Cash'), ('BANK', 'Bank Transfer'), ('MOBILE_BANKING', 'Mobile Banking'), ('CHEQUE', 'Cheque'), ('ONLINE', 'Online Payment')], max_length=20)),
                ('currency', models.CharField(max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('exchange_rate', models.DecimalField(decimal_places=4, max_digits=12)),
                ('euro_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('applicant_snapshot', models.JSONField(blank=True, default=dict)),
                ('staff_snapshot', models.JSONField(blank=True, default=dict)),
                ('visa_job_country_snapshot', models.JSONField(blank=True, default=dict)),
                ('payment_snapshot', models.JSONField(blank=True, default=dict)),
                ('summary_text', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_void', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='money_receipts', to='applicant.applicant')),
                ('generated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_money_receipts', to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='money_receipts', to='applicant.applicantpayment')),
            ],
            options={
                'verbose_name': 'Applicant Money Receipt',
                'verbose_name_plural': 'Applicant Money Receipts',
                'ordering': ['-generated_at', '-created_at'],
                'indexes': [models.Index(fields=['applicant', 'receipt_number'], name='applicant_a_applica_8300dd_idx'), models.Index(fields=['payment', 'is_active'], name='applicant_a_payment_55bb42_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='applicantrefund',
            index=models.Index(fields=['applicant', 'refund_status'], name='applicant_a_applica_e0128c_idx'),
        ),
        migrations.AddIndex(
            model_name='applicantrefund',
            index=models.Index(fields=['applicant', 'generated_from_rejection'], name='applicant_a_applica_c9f192_idx'),
        ),
        migrations.AddIndex(
            model_name='applicantrefundreceipt',
            index=models.Index(fields=['applicant', 'receipt_number'], name='applicant_a_applica_628208_idx'),
        ),
        migrations.AddIndex(
            model_name='applicantrefundreceipt',
            index=models.Index(fields=['refund', 'is_active'], name='applicant_a_refund__ab8589_idx'),
        ),
    ]
