# Generated by Django 6.0.6 on 2026-07-07 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0005_applicantprofile_preferred_refund_method'),
        ('visa', '0003_alter_visaseo_og_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='secondary_job',
            field=models.ForeignKey(blank=True, help_text='Optional secondary job choice.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='secondary_applicants', to='visa.visajob'),
        ),
    ]
