# Generated by Django 6.0.6 on 2026-07-03 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0005_applicant_payment_plan_installments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantmoneyreceipt',
            name='current_currency',
            field=models.CharField(blank=True, help_text='Current selected currency for this receipt entry.', max_length=3),
        ),
        migrations.AddField(
            model_name='applicantmoneyreceipt',
            name='euro',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Euro value for this receipt entry.', max_digits=12),
        ),
        migrations.AddField(
            model_name='applicantpayment',
            name='current_currency',
            field=models.CharField(blank=True, help_text='Current selected currency for this payment entry.', max_length=3),
        ),
        migrations.AddField(
            model_name='applicantpayment',
            name='euro',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Euro value for this payment entry.', max_digits=12),
        ),
    ]
