# Generated by Django 6.0.6 on 2026-07-10 16:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0006_applicant_secondary_job'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agreementtemplate',
            options={'ordering': ['sequence', '-version', 'title'], 'verbose_name': 'Agreement Template', 'verbose_name_plural': 'Agreement Templates'},
        ),
        migrations.RemoveConstraint(
            model_name='agreementtemplate',
            name='unique_agreement_type_version',
        ),
        migrations.RemoveIndex(
            model_name='applicantagreement',
            name='applicant_a_applica_fd6636_idx',
        ),
        migrations.AddField(
            model_name='agreementtemplate',
            name='sequence',
            field=models.PositiveIntegerField(db_index=True, default=1, help_text='Order in which this agreement appears.'),
        ),
        migrations.AddIndex(
            model_name='applicantagreement',
            index=models.Index(fields=['applicant'], name='applicant_a_applica_69f99c_idx'),
        ),
        migrations.AddConstraint(
            model_name='agreementtemplate',
            constraint=models.UniqueConstraint(fields=('sequence', 'version'), name='unique_sequence_version'),
        ),
        migrations.RemoveField(
            model_name='agreementtemplate',
            name='agreement_type',
        ),
        migrations.RemoveField(
            model_name='applicantagreement',
            name='agreement_type',
        ),
    ]
