# Generated by Django 6.0.6 on 2026-07-03 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0006_applicantmoneyreceipt_current_currency_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agreementtemplate',
            name='visa',
        ),
        migrations.AlterField(
            model_name='agreementtemplate',
            name='body',
            field=models.TextField(help_text='Supports dynamic placeholders such as {full_name}, {passport_number}, {visa}, {job}, {country}, {payment}, {staff}, and similar values.'),
        ),
    ]
