# Generated by Django 6.0.6 on 2026-07-11 08:44

import cloudinary.models
import core.validators
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0007_alter_agreementtemplate_options_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='currencyrate',
            name='unique_currency_rate_pair',
        ),
        migrations.RemoveField(
            model_name='applicantpayment',
            name='currency_rate',
        ),
        migrations.AlterField(
            model_name='applicant',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png']), core.validators.validate_image_size, core.validators.validate_profile_image_dimensions], verbose_name='image'),
        ),
        migrations.DeleteModel(
            name='CurrencyRate',
        ),
    ]
