# Generated by Django 6.0.6 on 2026-07-03 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0007_remove_agreementtemplate_visa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicantmoneyreceipt',
            name='current_currency',
        ),
        migrations.RemoveField(
            model_name='applicantmoneyreceipt',
            name='euro',
        ),
        migrations.RemoveField(
            model_name='applicantpayment',
            name='current_currency',
        ),
        migrations.RemoveField(
            model_name='applicantpayment',
            name='euro',
        ),
    ]
