# Generated by Django 6.0.6 on 2026-07-03 21:50

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0008_remove_applicantmoneyreceipt_current_currency_and_more'),
        ('country', '0004_rename_keywords_countryseo_meta_keywords'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgreementTemplateClause',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clause_key', models.SlugField(blank=True, help_text='Stable key such as refund-authorization.', max_length=160)),
                ('clause_number', models.PositiveIntegerField(default=1)),
                ('title_en', models.CharField(blank=True, max_length=255)),
                ('title_ar', models.CharField(blank=True, max_length=255)),
                ('title_bn', models.CharField(blank=True, max_length=255)),
                ('body_en', models.TextField(blank=True)),
                ('body_ar', models.TextField(blank=True)),
                ('body_bn', models.TextField(blank=True)),
                ('visibility_mode', models.CharField(choices=[('ALL', 'All Countries'), ('INCLUDE', 'Only Selected Countries'), ('EXCLUDE', 'Except Selected Countries')], default='ALL', max_length=20)),
                ('visibility_rules', models.JSONField(blank=True, default=dict, help_text='Optional future rules for status, visa, payment, refund, etc.')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Agreement Template Clause',
                'verbose_name_plural': 'Agreement Template Clauses',
                'ordering': ['template', 'clause_number', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApplicantAgreement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agreement_type', models.CharField(choices=[('MAIN', 'Main Agreement'), ('SECOND', 'Second Agreement'), ('THIRD', 'Third Agreement'), ('REFUND', 'Refund Agreement'), ('OTHER', 'Other Agreement')], db_index=True, default='MAIN', max_length=20)),
                ('language', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic'), ('bn', 'Bangla'), ('all', 'All Languages')], default='all', help_text='Preferred display language; rendered content stores all languages.', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('template_version', models.PositiveIntegerField(default=1)),
                ('rendered_content', models.JSONField(blank=True, default=dict, help_text='Rendered multilingual structured agreement clauses.')),
                ('rendered_text', models.JSONField(blank=True, default=dict, help_text='Rendered plain text by language for quick preview.')),
                ('context_snapshot', models.JSONField(blank=True, default=dict)),
                ('template_snapshot', models.JSONField(blank=True, default=dict)),
                ('generated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('is_void', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Applicant Agreement',
                'verbose_name_plural': 'Applicant Agreements',
                'ordering': ['-generated_at', '-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='agreementtemplate',
            options={'ordering': ['agreement_type', '-version', 'title'], 'verbose_name': 'Agreement Template', 'verbose_name_plural': 'Agreement Templates'},
        ),
        migrations.AddField(
            model_name='agreementtemplate',
            name='agreement_type',
            field=models.CharField(choices=[('MAIN', 'Main Agreement'), ('SECOND', 'Second Agreement'), ('THIRD', 'Third Agreement'), ('REFUND', 'Refund Agreement'), ('OTHER', 'Other Agreement')], db_index=True, default='MAIN', max_length=20),
        ),
        migrations.AddField(
            model_name='agreementtemplate',
            name='code',
            field=models.SlugField(blank=True, help_text='Stable API/admin code for this agreement template.', max_length=160, unique=True),
        ),
        migrations.AddField(
            model_name='agreementtemplate',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='agreementtemplate',
            name='is_default',
            field=models.BooleanField(default=False, help_text='Can be generated automatically for new applicants.'),
        ),
        migrations.AddField(
            model_name='agreementtemplate',
            name='title_ar',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='agreementtemplate',
            name='title_bn',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='agreementtemplate',
            name='title_en',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='agreementtemplate',
            name='body',
            field=models.TextField(blank=True, default='', help_text='Legacy fallback body. Prefer structured clauses. Supports dynamic placeholders such as {full_name}, {passport_number}, {visa}, {job}, {country}, {payment}, {staff}, and similar values.'),
        ),
        migrations.AddConstraint(
            model_name='agreementtemplate',
            constraint=models.UniqueConstraint(fields=('agreement_type', 'version'), name='unique_agreement_type_version'),
        ),
        migrations.AddField(
            model_name='agreementtemplateclause',
            name='countries',
            field=models.ManyToManyField(blank=True, help_text='Used with visibility_mode. INCLUDE means only these countries; EXCLUDE means hide for these countries.', related_name='agreement_clauses', to='country.country'),
        ),
        migrations.AddField(
            model_name='agreementtemplateclause',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clauses', to='applicant.agreementtemplate'),
        ),
        migrations.AddField(
            model_name='applicantagreement',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='applicant.applicant'),
        ),
        migrations.AddField(
            model_name='applicantagreement',
            name='generated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_applicant_agreements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='applicantagreement',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applicant_agreements', to='applicant.agreementtemplate'),
        ),
        migrations.AddConstraint(
            model_name='agreementtemplateclause',
            constraint=models.UniqueConstraint(fields=('template', 'clause_number'), name='unique_agreement_template_clause_number'),
        ),
        migrations.AddIndex(
            model_name='applicantagreement',
            index=models.Index(fields=['applicant', 'agreement_type'], name='applicant_a_applica_fd6636_idx'),
        ),
        migrations.AddIndex(
            model_name='applicantagreement',
            index=models.Index(fields=['template', 'is_active'], name='applicant_a_templat_4eb067_idx'),
        ),
    ]
