# Generated by Django 6.0.6 on 2026-07-12 14:42

from django.db import migrations
from django.utils.text import slugify

def seed_statuses(apps, schema_editor):
    ApplicationStatus = apps.get_model("applicant", "ApplicationStatus")

    statuses = [
        ("Disable", "Initial inactive status.", True, False),
        ("1st Payment recieved", "The first installment has been received.", False, False),
        ("Profile Created", "Profile created.", False, False),
        ("Documents Received", "Documents received.", False, False),
        ("Documents Verified", "Documents verified.", False, False),
        ("Application Registered", "Application registered.", False, False),
        ("Application Approved", "Application approved.", False, False),
        ("Payment Confirmed", "Payment confirmed.", False, False),
        ("Profile Activated", "Profile activated.", False, False),
        ("Employer Submission Started", "Employer submission started.", False, False),
        ("Shortlisted by Employer", "Shortlisted by employer.", False, False),
        ("Employer Selected / Job Offer Issued", "Job offer issued.", False, False),
        ("Work Authorization Processing", "Work authorization processing.", False, False),
        ("Visa File Preparation", "Visa file preparation.", False, False),
        ("Visa Application Submitted", "Visa application submitted.", False, False),
        ("Visa Approved", "Visa approved.", False, False),
        ("Travel Arrangements", "Travel arrangements.", False, False),
        ("Departure Scheduled", "Departure scheduled.", False, False),
        ("Arrived at Destination", "Arrived at destination.", False, False),
        ("Process Successfully Completed", "Process successfully completed.", False, True),
        ("Rejected", "Application rejected.", False, True),
    ]

    for index, (name, desc, is_default, is_final) in enumerate(statuses, start=1):
        # We handle "First Payment Received" if it was already created, updating it to the exact new name.
        if name == "1st Payment recieved":
            old_first = ApplicationStatus.objects.filter(slug="first-payment-received").first()
            if old_first:
                old_first.name = name
                old_first.slug = slugify(name)
                old_first.display_order = index
                old_first.save()
                continue
                
        status, created = ApplicationStatus.objects.get_or_create(
            slug=slugify(name),
            defaults={
                "name": name,
                "description": desc,
                "is_default": is_default,
                "is_final": is_final,
                "display_order": index,
                "is_active": True,
            }
        )
        if not created:
            status.name = name
            status.is_default = is_default
            status.is_final = is_final
            status.display_order = index
            status.save(update_fields=["name", "is_default", "is_final", "display_order"])
            
    # Ensure only Disable is default
    disable_status = ApplicationStatus.objects.get(slug=slugify("Disable"))
    ApplicationStatus.objects.exclude(pk=disable_status.pk).update(is_default=False)

def reverse_seed_statuses(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0008_remove_currencyrate_unique_currency_rate_pair_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_statuses, reverse_seed_statuses),
    ]
