# Generated by Django 6.0.6 on 2026-07-04 11:46

import secrets
import string
from django.db import migrations, models


PREFIX = "ARG"
SUFFIX_LENGTH = 5
ALPHABET = string.ascii_uppercase + string.digits


def generate_public_application_id(existing_ids):
    for _ in range(100):
        suffix = "".join(
            secrets.choice(ALPHABET)
            for _ in range(SUFFIX_LENGTH)
        )
        application_id = f"{PREFIX}{suffix}"

        if application_id not in existing_ids:
            existing_ids.add(application_id)
            return application_id

    raise RuntimeError("Unable to generate a unique application ID.")


def migrate_application_ids(apps, schema_editor):
    Applicant = apps.get_model("applicant", "Applicant")
    existing_ids = set()

    for applicant in Applicant.objects.order_by("created_at", "id"):
        current_id = applicant.application_id or ""

        if (
            len(current_id) == 8
            and current_id.startswith(PREFIX)
            and current_id not in existing_ids
        ):
            existing_ids.add(current_id)
            continue

        applicant.application_id = generate_public_application_id(
            existing_ids,
        )
        applicant.save(
            update_fields=[
                "application_id",
            ],
        )


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0009_agreementtemplateclause_applicantagreement_and_more'),
    ]

    operations = [
        migrations.RunPython(
            migrate_application_ids,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='applicant',
            name='application_id',
            field=models.CharField(db_index=True, editable=False, max_length=8, unique=True),
        ),
    ]
