# Generated by Django 6.0.6 on 2026-07-21 04:59

import cloudinary.models
import core.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0009_seed_all_statuses'),
        ('country', '0004_alter_countryrequirement_requirement_type'),
        ('visa', '0004_alter_visarequirement_requirement_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FakeLiveResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant_name', models.CharField(max_length=200)),
                ('application_id', models.CharField(db_index=True, max_length=8)),
                ('passport_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('photo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png']), core.validators.validate_image_size], verbose_name='image')),
                ('result_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='country.country')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visa.visajob')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applicant.applicationstatus')),
                ('visa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visa.visa')),
            ],
            options={
                'verbose_name': 'Fake Live Result',
                'verbose_name_plural': 'Fake Live Results',
                'ordering': ['-result_date'],
            },
        ),
    ]
