# Generated by Django 6.0.6 on 2026-07-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0010_fakeliveresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='application_id',
            field=models.CharField(blank=True, db_index=True, help_text='Optional custom application ID entered by admin.', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
