# Generated by Django 6.0.6 on 2026-07-24 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0011_alter_applicant_application_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantmoneyreceipt',
            name='important_note',
            field=models.TextField(blank=True, default='', help_text='Important note printed on money receipt.'),
        ),
        migrations.AddField(
            model_name='applicantpayment',
            name='important_note',
            field=models.TextField(blank=True, default='', help_text='Important note printed on money receipt.'),
        ),
    ]
