# Generated by Django 6.0.6 on 2026-07-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0012_applicantmoneyreceipt_important_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fakeliveresult',
            name='application_id',
            field=models.CharField(db_index=True, max_length=50),
        ),
    ]
