# Generated by Django 6.0.6 on 2026-07-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0013_alter_fakeliveresult_application_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='send_email_on_status_change',
            field=models.BooleanField(default=True, help_text='If enabled, updating applicant status automatically dispatches notification emails.'),
        ),
    ]
