# Generated by Django 6.0.6 on 2026-07-27 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0014_applicant_send_email_on_status_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicantpayment',
            name='countdown_days',
            field=models.PositiveIntegerField(blank=True, help_text='Target countdown days for status tracking.', null=True),
        ),
        migrations.AlterField(
            model_name='applicantmoneyreceipt',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=8, max_digits=18),
        ),
        migrations.AlterField(
            model_name='applicantpayment',
            name='exchange_rate',
            field=models.DecimalField(decimal_places=8, help_text='Exchange rate used during payment.', max_digits=18),
        ),
    ]
