# Generated by Django 6.0.6 on 2026-08-30 10:51

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0015_applicantpayment_countdown_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantprofile',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=20, validators=[core.validators.validate_phone_number]),
        ),
    ]
