# Generated by Django 6.0.6 on 2026-08-30 11:04

import cloudinary.models
import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0016_alter_applicantprofile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='payment_plan_installments',
            field=models.PositiveSmallIntegerField(choices=[(1, 'One Installment'), (2, 'Two Installments'), (3, 'Three Installments'), (4, 'Four Installments')], default=2, help_text='Total expected payment installments for this applicant.'),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), core.validators.validate_image_size, core.validators.validate_profile_image_dimensions], verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='applicantdocument',
            name='file',
            field=cloudinary.models.CloudinaryField(max_length=255, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'jpg', 'jpeg', 'png', 'webp']), core.validators.validate_document_size], verbose_name='raw'),
        ),
        migrations.AlterField(
            model_name='applicantprofile',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='fakeliveresult',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp']), core.validators.validate_image_size], verbose_name='image'),
        ),
    ]
