# Generated by Django 6.0.6 on 2026-08-30 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applicant', '0018_alter_applicant_payment_plan_installments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='payment_plan_installments',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Two Installments'), (3, 'Three Installments')], default=2, help_text='Total expected payment installments for this applicant.'),
        ),
    ]
